<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CleanArchitecture_IMS.UseCases</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanArchitecture-IMS.CoreEntities\CleanArchitecture-IMS.CoreEntities.csproj" />
  </ItemGroup>

</Project>
